# Generated by Django 5.0.2 on 2024-02-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('champion', models.CharField(max_length=50)),
                ('kills', models.IntegerField(max_length=3)),
                ('deaths', models.IntegerField(max_length=3)),
                ('assists', models.IntegerField(max_length=3)),
                ('wards', models.IntegerField(max_length=3)),
                ('duracao', models.IntegerField(max_length=5)),
                ('farm', models.IntegerField(max_length=5)),
                ('ouro', models.IntegerField(max_length=6)),
                ('win', models.BooleanField()),
                ('creation_time', models.DateTimeField()),
                ('total_ouro', models.IntegerField(max_length=7)),
                ('total_kills', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=16, unique=True)),
                ('level', models.IntegerField(max_length=5)),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
    ]
