# Generated by Django 5.0.2 on 2024-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='riot_id',
            field=models.CharField(default=None, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
