# Generated by Django 5.0.2 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0002_player_riot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deaths',
        ),
        migrations.RemoveField(
            model_name='game',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='game',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='game',
            name='kills',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ouro',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_kills',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_ouro',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.AddField(
            model_name='player',
            name='puuid',
            field=models.CharField(default=0, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='riot_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='summoner_name',
            field=models.CharField(max_length=16),
        ),
    ]
