# Generated by Django 5.0.2 on 2024-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0003_remove_game_assists_remove_game_deaths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='assists',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='deaths',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='duracao',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='farm',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='kills',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ouro',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='total_kills',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='total_ouro',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='wards',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='puuid',
            field=models.CharField(max_length=78, unique=True),
        ),
    ]
