# Generated by Django 5.0.2 on 2024-02-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0005_alter_player_puuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_kills',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_ouro',
        ),
    ]
