# Generated by Django 5.0.2 on 2024-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0006_remove_game_total_kills_remove_game_total_ouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='win',
            field=models.CharField(max_length=4),
        ),
    ]
