# Generated by Django 5.0.2 on 2024-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riotapp', '0007_alter_game_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duracao',
            field=models.CharField(max_length=8),
        ),
    ]
